[package]
name = "justethecoder/sharp"
description = "A lightweight framework for Roblox."
license = "MIT"
version = "0.1.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = [".gitingore", ".gitattributes"]

[dependencies]